#### 此次作業所使用的資料集是老師提供新聞資料集，老師一共有提供十個資料集，因為我的學號末四碼是5422，所以我選擇的資料集分別是0體育、2社會、4科技和5娛樂，因為2重複所以我隨意挑選0體育做為第四個以上的每個資料集都有1000篇新聞文字檔，作業的目標是要將此4000篇新聞讓神經網路去做學習，學習完之後讓電腦去做新聞的分類。

## 此次作業的資料集和以前所需要做的前處理不太相同，主要原因是電腦只能讀數字，但此次作業是做文字的分類任務，所以通常會在讓電腦學習前會先將文字經過一系列的特殊處理，之後才會進到分類器的任務。以下將會逐步介紹前處理的步驟:
### 1. 載入資料將體育、社會、科技以及娛樂新聞資料夾讀進list中

In [1]:
import os

path = '5娛樂/'
lines1 =[]
for filename in os.listdir(path):
    if os.path.isfile(path + filename) and filename.endswith(".txt"):
        with open(path + filename, "r", encoding= 'utf-8') as file:
            data = file.read()
            lines1.append(data)

path = '4科技/'
lines2 =[]
for filename in os.listdir(path):
    if os.path.isfile(path + filename) and filename.endswith(".txt"):
        with open(path + filename, "r", encoding= 'utf-8') as file:
            data = file.read()
            lines2.append(data)
            
path = '2社會/'
lines3 =[]
for filename in os.listdir(path):
    if os.path.isfile(path + filename) and filename.endswith(".txt"):
        with open(path + filename, "r", encoding= 'utf-8') as file:
            data = file.read()
            lines3.append(data)

path = '0體育/'
lines4 =[]
for filename in os.listdir(path):
    if os.path.isfile(path + filename) and filename.endswith(".txt"):
        with open(path + filename, "r", encoding= 'utf-8') as file:
            data = file.read()
            lines4.append(data)

### 2 .載入停用詞：為節省存儲空間和提高搜索效率，在處理自然語言數據（或文本）之前或之後會自動過濾掉某些字或詞，這些字或詞即被稱為Stop Words(停用詞)。此次作業所使用的資料集都是以簡體字為主的新聞，使用的停用詞表共有4個，分別為中文停用詞表、四川大學機器智能實驗室停用詞庫、百度停用詞表和哈工大停用詞表，將停用詞表分別載入後，利用pandas模組裡的concat方法將所有的停用詞表集合為一個陣列


In [2]:
import pandas as pd
stopwords = []
stopwords1=pd.read_csv('中文停用词表.txt',index_col=False,quoting=3,sep="\t", names=['stopword'], encoding='utf-8')
stopwords2=pd.read_csv('四川大学机器智能实验室停用词库.txt',index_col=False,quoting=3,sep="\t", names=['stopword'], encoding='utf-8')
stopwords3=pd.read_csv('百度停用词表.txt',index_col=False,quoting=3,sep="\t", names=['stopword'], encoding='utf-8')
stopwords4=pd.read_csv('哈工大停用词表.txt',index_col=False,quoting=3,sep="\t", names=['stopword'], encoding='utf-8')
st = pd.concat([stopwords1,stopwords2,stopwords3,stopwords4]).squeeze(1)
stopwords=st.values

In [3]:
stopwords

array(['$', '0', '1', ..., '嗬', '嗯', '嗳'], dtype=object)

### 3. 文字前處理：這邊是 利用老師的preprocess_text方法&結巴斷詞、去數字、去左右空格、去掉長度為1的文字與符號，最後去除停用詞，在各自將同一類的新聞給予同一個數字label。


In [4]:
import jieba
from tqdm import tqdm_notebook,tqdm
#定義分詞和打標簽函數preprocess_text
#參數content_lines即為上面轉換的list
#參數sentences是定義的空list，用來儲存打標簽之後的數據
#參數category 是類型標簽
def preprocess_text(content_lines, classlabel):
    sentences =[]
    categories = []
    for line in tqdm_notebook(content_lines):
        segs=jieba.lcut(line)
        segs = [v for v in segs if not str(v).isdigit()]#去數字
        segs = list(filter(lambda x:x.strip(), segs))   #去左右空格
        segs = list(filter(lambda x:len(x)>1, segs)) #長度為1的字符
        segs = list(filter(lambda x:x not in stopwords, segs)) #去掉停用詞
        sentences.append(segs)
        categories.append(classlabel)
 
    
    return sentences, categories

In [5]:
X1, y1 = preprocess_text(lines1, 0)
X2, y2 = preprocess_text(lines2, 1)
X3, y3 = preprocess_text(lines3, 2)
X4, y4 = preprocess_text(lines4, 3)
X = X1 + X2 + X3 + X4
y = y1 + y2 + y3 + y4

C:\Users\User\Anaconda3\envs\unityyyyy\lib\site-packages\ipykernel_launcher.py:10: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  # Remove the CWD from sys.path while we load stuff.


Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\User\AppData\Local\Temp\jieba.cache
Loading model cost 0.472 seconds.
Prefix dict has been built successfully.


In [6]:
y

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


### 4. 生成字典和向量語料：將出現至少一次以上的詞創建字典，意即有多少組成不一樣的詞字典就會有多大，這會影響到後面神經網路輸出features的大小。

In [7]:
# gensim modules
import gensim
from gensim import utils
from gensim import corpora,models


dictionary = corpora.Dictionary(X)
corpus = [dictionary.doc2bow(text) for text in X]

#### tf-idf：利用gensim的TfidfModel進行語料庫的初始化，在tf-idf的轉化中，訓練的過程中就是簡單的遍歷訓練語料庫，然後計算文本中每個特徵(詞)的頻率。


In [8]:
model = models.TfidfModel(corpus)
corpus = [text for text in tqdm_notebook(model[corpus])]
X = gensim.matutils.corpus2dense(corpus, num_terms=len(dictionary.token2id)).T

C:\Users\User\Anaconda3\envs\unityyyyy\lib\site-packages\ipykernel_launcher.py:2: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  


In [9]:
import torch
import matplotlib.pyplot as plt
import torch.nn.functional as F

### 5. 將label做one hot encoder，將四個標籤都做one hot encoder的處理。


In [10]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import numpy as np
enc = OneHotEncoder()
Y = enc.fit_transform(np.array(y).reshape(-1,1)).toarray()

### 6. 訓練資料與測試資料分群：這次的訓練與測試資料分群，根據老師的作業要求，將資料分成訓練測試分別為0.8和0.2，隨機的種子皆設為15。


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=15)

In [12]:
print(Y_train)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [13]:
print(X_train.shape)
print(Y_test.shape)

(3200, 66715)
(800, 4)


## 由於神經網路需要長時間訓練，原本依照老師的程式碼是使用keras的程式碼，主要是丟給CPU去訓練，但是CPU訓練的時間需要非常久，因此決定運用GPU去進行訓練，輸入資料必須丟進cuda才會可以實驗，文字資料部分會轉成有小數的Float tensor資料型態，標籤因為經過one hot encoder，數字不是0就是1，所以會轉成Long tensor的資料型態

In [14]:
tensorX_train = torch.FloatTensor(X_train).cuda()
tensorX_test = torch.FloatTensor(X_test).cuda()
tensory_train = torch.LongTensor(Y_train).cuda()
tensory_test = torch.LongTensor(Y_test).cuda()

In [15]:
tensorX_train.shape

torch.Size([3200, 66715])

## 7. 建立神經網路：
#### 定義網路層數、輸入輸出節點，定義學習優化器(RELU 、Sigmoid)，再定義損失函數，為了預防模型過度凝合，最後將模型丟進cuda，才能讓GPU去做運算

In [16]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.L1 = torch.nn.Linear(66715, 2048)
        torch.nn.Dropout(p=0.5)
        self.L2 = torch.nn.Linear(2048, 4)
    def forward(self, x):
        x = torch.relu(self.L1(x))
        x = self.L2(x)
        return x
net = Net().cuda()
net

Net(
  (L1): Linear(in_features=66715, out_features=2048, bias=True)
  (L2): Linear(in_features=2048, out_features=4, bias=True)
)

## 8.定義學習率：控制著我們基於損失梯度調整神經網絡權值的速度，大多數優化算法（如SGD、RMSprop、Adam），學習率越小，我們沿著損失梯度下降的速度越慢，可以避免錯過任何局部最優解，相對謹慎慢行，但它也意味著我們要花更多時間來收斂，尤其是如果我們處於曲線的至高點，而學習率越大，則學習效率越高，所花費時間也較小。

In [17]:
optimizer = torch.optim.Adam(net.parameters(), lr = 1e-4)

#### 定義學習優化器：使用的損失函數為交叉熵(cross entropy)

In [18]:
loss_function = torch.nn.CrossEntropyLoss().cuda()

In [19]:
from IPython import display
trainloss = []
testloss = []
acctrain = []
accstest = []

### 定義準確率：根據網路上常做文本分類準確率來做定義，準確率為如果當下被分類的文本被電腦歸類的正不正確，如果正確則變數correct做+1的動作，錯誤則+0，計算完全部以後，將變數correct去除以所有的文本數，以變數表示為accuracy = correct / total

In [ ]:
trainloss = []
testloss = []
for epoch in tqdm(range(100)):
    net.train()
    running_loss = 0.0
    for features in tqdm_notebook(range(len(tensorX_train))):
        optimizer.zero_grad()
        y_pred = net(tensorX_train[features]).unsqueeze(0)
        labels = torch.argmax(tensory_train[features]).unsqueeze(0)
        loss = loss_function(y_pred,labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    trainloss.append(running_loss)
     
    net.eval()
    total = 0
    correct = 0
    acc = 0
    for index in tqdm_notebook(range(len(tensorX_train))):
        y_pred = net(tensorX_train[index])
        _, pred = torch.max(y_pred.data,0)
        labels = torch.argmax(tensory_train[index])
        total = len(tensory_train)
        correct += (int(pred) == labels).sum().item()
    acc = correct / total
    acctrain.append(acc)
    print(f'epoch = {epoch + 1} , train data loss = {running_loss} , acc = {acc}  , correct = {correct}  ,  total = {total}')
    runningtest_loss = 0.0
    totaltest = 0
    correcttest = 0
    acctest = 0
    
    for index in tqdm_notebook(range(len(tensorX_test))):
        y_predtest = net(tensorX_test[index]).unsqueeze(0)
        predtest = torch.argmax(y_predtest.data)
        labelstest = torch.argmax(tensory_test[index]).unsqueeze(0)
        totaltest = len(tensorX_test)
        correcttest += (predtest == labelstest).sum().item()
        losstest = loss_function(y_predtest,labelstest)
        runningtest_loss += losstest.item()
    accstest.append(acc)
    testloss.append(runningtest_loss)
    acctest = correcttest / totaltest
    print(f'epoch = {epoch + 1} , test data loss = {runningtest_loss} , acc = {acctest}  , correct = {correcttest}  ,  total = {totaltest}')
    
    display.clear_output(wait=True)
    fig, (ax1, ax2) = plt.subplots(2,figsize=(15,15))
    ax1.plot(acctrain,'--',color='SteelBlue', label='Train Data Accuracy')
    ax1.plot(accstest,'-',color='RosyBrown', label='Test Data Accuracy')
    ax1.set_title('Accuracy')
    ax1.legend(loc='upper left')
    
    ax2.plot(trainloss,'--',color='SteelBlue', label='Train Data Loss')
    ax2.plot(testloss ,'-',color='RosyBrown', label='Test Data Loss')
    ax2.set_title('Loss')
    ax2.legend(loc='upper left')
    plt.show()    

  0%|                                                                                          | 0/100 [00:00<?, ?it/s]C:\Users\User\Anaconda3\envs\unityyyyy\lib\site-packages\ipykernel_launcher.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split   #訓練 & 測試資料
X_train, X_test, y_train, y_test = train_test_split(X, y)
classifier = MultinomialNB()
# should be classifier.fit(X_train, y_train) but changed to
#classifier.fit(X, y)
classifier.fit(X_train, y_train)

pre = classifier.predict(X_test)

print(classification_report(pre, y_test))

#### 作業中，我調整了網路深度、節點數、學習率、優化器、節點隨機丟棄，在這些實驗中最高的準確率達0.8以上。不過是前幾個迴圈(epoch=5)、就到達此正確率，我懷疑是Adam優化器的震盪，在前幾個迴圈準確率就達到非常高(0.75)，但後幾個迴圈就明顯過度學習了。因此我推測是優化器的不同造成此原因，Adam很快就有可能到達模型最佳、而SGD反而都需要很久才會到達最高，此次資料集是Adam函數較優，不過也很容易就過度學習。從上述實驗中可以稍微觀察到，以優化器來說，adam最好結果是約0.78，SGD最後結果為約0.8以上、Adam很容易到達最佳解，但也容易過度訓練，SGD相對會花較多時間，而且並不一定會到達最佳解。原本有跑了100迴圈但調整參數後要重新跑，因此改為10次迴圈，途中因不停重複改參數與捲基層等過程，沒有紀錄所以以目前最高準確率的模型進行呈現。由於為了提升效率才改用Pytorch。
#### 從混淆矩陣的程式，可以看出此四個資料集中，有兩個資料集容易在分類任務中讓電腦造成混淆(娛樂及科技新聞)，所以造成神經網路(ANN)訓練準確率不容易突破0.8。